server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA — toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Désactiver le cache sur index.html (mise à jour sans hard-refresh)
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
